import type { RouteOption, RouteResult } from "@/lib/types";

/**
 * Simulated routing engine.
 * Replace calculateRoute() with Google Maps / Mapbox / OpenRouteService later.
 */

type CityPair = {
  from: string;
  to: string;
  recommended: RouteOption;
  alternative: RouteOption;
};

const KNOWN_ROUTES: CityPair[] = [
  {
    from: "Kolkata",
    to: "Bhubaneswar",
    recommended: {
      name: "NH-16 coastal corridor",
      distanceKm: 440,
      etaMinutes: 500,
      traffic: "Moderate",
      notes: "Primary freight highway via Kharagpur and Balasore.",
    },
    alternative: {
      name: "NH-16 + SH-9 inland",
      distanceKm: 465,
      etaMinutes: 525,
      traffic: "Light",
      notes: "Slightly longer but fewer urban bottlenecks.",
    },
  },
  {
    from: "NH-16",
    to: "Bhubaneswar",
    recommended: {
      name: "Continue NH-16 south",
      distanceKm: 165,
      etaMinutes: 200,
      traffic: "Moderate",
      notes: "Original planned corridor.",
    },
    alternative: {
      name: "Detour via Bhadrak–Cuttack",
      distanceKm: 182,
      etaMinutes: 225,
      traffic: "Light",
      notes: "Avoids the blocked stretch near the incident.",
    },
  },
];

function normalize(value: string) {
  return value.trim().toLowerCase();
}

function fallbackPair(from: string, to: string): CityPair {
  const seed = from.length + to.length;
  const distanceKm = 180 + seed * 7;
  return {
    from,
    to,
    recommended: {
      name: `Fastest simulated corridor (${from} → ${to})`,
      distanceKm,
      etaMinutes: Math.round(distanceKm * 1.15),
      traffic: "Moderate",
      notes: "Generated by the prototype router. Swap this function for a live routing API.",
    },
    alternative: {
      name: `Alternate highway (${from} → ${to})`,
      distanceKm: distanceKm + 25,
      etaMinutes: Math.round((distanceKm + 25) * 1.12),
      traffic: "Light",
      notes: "Secondary route used when the primary corridor is blocked.",
    },
  };
}

export function formatEta(minutes: number) {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  if (h <= 0) return `${m}m`;
  return `${h}h ${m.toString().padStart(2, "0")}m`;
}

export function calculateRoute(from: string, to: string, truckId: string): RouteResult {
  const match = KNOWN_ROUTES.find(
    (row) => normalize(row.from) === normalize(from) && normalize(row.to) === normalize(to),
  );
  const pair = match ?? fallbackPair(from, to);
  return {
    from,
    to,
    truckId,
    recommended: pair.recommended,
    alternative: pair.alternative,
  };
}

/** Used after an emergency: returns original vs detour ETAs. */
export function calculateEmergencyReroute(from: string, to: string, truckId: string) {
  const result = calculateRoute(from, to, truckId);
  const delay = result.alternative.etaMinutes - result.recommended.etaMinutes;
  return {
    ...result,
    delayMinutes: delay,
    message: `Alternative route found. Delivery delay estimated at ${delay} minutes.`,
  };
}
